spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dpp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
#    url: jdbc:mysql://192.168.0.90:3306/dpp?useUnicode=true&characterEncoding=UTF-8
#    username: sziov
#    password: sziov


  redis:
    database: 2
    host: localhost
    port: 7001
    password: 123456
    timeout: 10000ms
    jedis:
      pool:
        max-active: 50
        max-wait: 10000ms
        max-idle: 50
        min-idle: 10
    max-total: 1001
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    num-tests-per-eviction-run: 1000
    time-between-eviction-runs-millis: 60000
    block-when-exhausted: false

logging:
  config: classpath:logback-spring-local.xml
server:
  port: 3001
spark:
  master: local[1]
  appNamePrefix: qb_energy_consumption_analysis
business:
  checkIntervalMillis: 10000
  redis-info:
    run-key: qb_energy_consumption_analysis
    run-info:
      name: D++续航能耗分析模型
  kafka:
    bootstrap-servers: d3.cdh.com:9092,d4.cdh.com:9092,d5.cdh.com:9092
#    bootstrap-servers: 192.168.0.65:9092
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    group-id: qb_test_cw_09
    auto-offset-reset: earliest
    initialRate: 20
    maxRatePerPartition: 20
    topics:
#      - tbox_period_1s
      - tbox_period_5s
#      - tbox_period_30s
#      - tbox_period_60s
#      - tbox_event_msg
